"""empty message

Revision ID: 015cd64e151a
Revises: 59202d403b5f
Create Date: 2021-05-09 01:29:53.422830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015cd64e151a'
down_revision = '59202d403b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('website_setting', sa.Column('setting_group', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('website_setting', 'setting_group')
    # ### end Alembic commands ###
