"""empty message

Revision ID: 06a3b333c4b3
Revises: 1baf958d7758
Create Date: 2021-05-05 12:48:15.197538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a3b333c4b3'
down_revision = '1baf958d7758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_platform')
    op.drop_column('game', 'max_graphics')
    op.drop_column('game', 'min_os')
    op.drop_column('game', 'max_memory')
    op.drop_column('game', 'min_processor')
    op.drop_column('game', 'min_graphics')
    op.drop_column('game', 'min_memory')
    op.drop_column('game', 'max_os')
    op.drop_column('game', 'min_storage')
    op.drop_column('game', 'max_processor')
    op.drop_column('game', 'max_storage')
    op.add_column('platform', sa.Column('game_id', sa.Integer(), nullable=True))
    op.add_column('platform', sa.Column('max_graphics', sa.String(length=60), nullable=True))
    op.add_column('platform', sa.Column('max_memory', sa.String(length=60), nullable=True))
    op.add_column('platform', sa.Column('max_os', sa.String(length=60), nullable=True))
    op.add_column('platform', sa.Column('max_processor', sa.String(length=60), nullable=True))
    op.add_column('platform', sa.Column('max_storage', sa.String(length=60), nullable=True))
    op.add_column('platform', sa.Column('min_graphics', sa.String(length=60), nullable=True))
    op.add_column('platform', sa.Column('min_memory', sa.String(length=60), nullable=True))
    op.add_column('platform', sa.Column('min_os', sa.String(length=60), nullable=True))
    op.add_column('platform', sa.Column('min_processor', sa.String(length=60), nullable=True))
    op.add_column('platform', sa.Column('min_storage', sa.String(length=60), nullable=True))
    op.create_foreign_key(None, 'platform', 'game', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'platform', type_='foreignkey')
    op.drop_column('platform', 'min_storage')
    op.drop_column('platform', 'min_processor')
    op.drop_column('platform', 'min_os')
    op.drop_column('platform', 'min_memory')
    op.drop_column('platform', 'min_graphics')
    op.drop_column('platform', 'max_storage')
    op.drop_column('platform', 'max_processor')
    op.drop_column('platform', 'max_os')
    op.drop_column('platform', 'max_memory')
    op.drop_column('platform', 'max_graphics')
    op.drop_column('platform', 'game_id')
    op.add_column('game', sa.Column('max_storage', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.add_column('game', sa.Column('max_processor', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.add_column('game', sa.Column('min_storage', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.add_column('game', sa.Column('max_os', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.add_column('game', sa.Column('min_memory', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.add_column('game', sa.Column('min_graphics', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.add_column('game', sa.Column('min_processor', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.add_column('game', sa.Column('max_memory', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.add_column('game', sa.Column('min_os', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.add_column('game', sa.Column('max_graphics', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.create_table('game_platform',
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('platform_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name='game_platform_game_id_fkey'),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], name='game_platform_platform_id_fkey')
    )
    # ### end Alembic commands ###
