"""empty message

Revision ID: 10ad2a380bb9
Revises: 533ad4e4fc3a
Create Date: 2021-05-04 18:09:46.302477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ad2a380bb9'
down_revision = '533ad4e4fc3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'price',
               existing_type=sa.NUMERIC(precision=2, scale=2),
               type_=sa.Numeric(precision=38, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'price',
               existing_type=sa.Numeric(precision=38, scale=2),
               type_=sa.NUMERIC(precision=2, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
