"""empty message

Revision ID: 1baf958d7758
Revises: 3b09f1752531
Create Date: 2021-05-04 23:34:41.119524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1baf958d7758'
down_revision = '3b09f1752531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'image_banner',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.alter_column('game', 'image_main',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=120),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'image_main',
               existing_type=sa.String(length=120),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    op.alter_column('game', 'image_banner',
               existing_type=sa.String(length=120),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    # ### end Alembic commands ###
