"""empty message

Revision ID: 278efc1a7020
Revises: 779decdac593
Create Date: 2021-05-08 21:06:28.078784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '278efc1a7020'
down_revision = '779decdac593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'discount',
               existing_type=sa.NUMERIC(precision=2, scale=2),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'discount',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=2, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
