"""empty message

Revision ID: 303de1a7b1cd
Revises: 2362ff01f32a
Create Date: 2021-05-04 15:17:05.372281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303de1a7b1cd'
down_revision = '2362ff01f32a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('game_platform',
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], )
    )
    op.create_table('game_tag',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    op.create_table('owned_games',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], )
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('review_title', sa.String(length=60), nullable=False),
    sa.Column('review_text', sa.String(length=4000), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('date_published', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('game', sa.Column('developer', sa.String(length=60), nullable=False))
    op.add_column('game', sa.Column('features', sa.Text(), nullable=False))
    op.add_column('game', sa.Column('languages', sa.String(length=60), nullable=False))
    op.add_column('game', sa.Column('max_graphics', sa.String(length=60), nullable=False))
    op.add_column('game', sa.Column('max_memory', sa.String(length=60), nullable=False))
    op.add_column('game', sa.Column('max_os', sa.String(length=60), nullable=False))
    op.add_column('game', sa.Column('max_processor', sa.String(length=60), nullable=False))
    op.add_column('game', sa.Column('max_storage', sa.String(length=60), nullable=False))
    op.add_column('game', sa.Column('min_graphics', sa.String(length=60), nullable=False))
    op.add_column('game', sa.Column('min_memory', sa.String(length=60), nullable=False))
    op.add_column('game', sa.Column('min_os', sa.String(length=60), nullable=False))
    op.add_column('game', sa.Column('min_processor', sa.String(length=60), nullable=False))
    op.add_column('game', sa.Column('min_storage', sa.String(length=60), nullable=False))
    op.add_column('game', sa.Column('other_details', sa.Text(), nullable=False))
    op.add_column('game', sa.Column('publisher', sa.String(length=60), nullable=False))
    op.add_column('game', sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=False))
    op.add_column('game', sa.Column('status', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'status')
    op.drop_column('game', 'rating')
    op.drop_column('game', 'publisher')
    op.drop_column('game', 'other_details')
    op.drop_column('game', 'min_storage')
    op.drop_column('game', 'min_processor')
    op.drop_column('game', 'min_os')
    op.drop_column('game', 'min_memory')
    op.drop_column('game', 'min_graphics')
    op.drop_column('game', 'max_storage')
    op.drop_column('game', 'max_processor')
    op.drop_column('game', 'max_os')
    op.drop_column('game', 'max_memory')
    op.drop_column('game', 'max_graphics')
    op.drop_column('game', 'languages')
    op.drop_column('game', 'features')
    op.drop_column('game', 'developer')
    op.drop_table('review')
    op.drop_table('owned_games')
    op.drop_table('game_tag')
    op.drop_table('game_platform')
    op.drop_table('tag')
    op.drop_table('platform')
    # ### end Alembic commands ###
