"""empty message

Revision ID: 3b09f1752531
Revises: 10ad2a380bb9
Create Date: 2021-05-04 21:48:13.062444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b09f1752531'
down_revision = '10ad2a380bb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('image_banner', sa.LargeBinary(), nullable=True))
    op.add_column('game', sa.Column('image_main', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'image_main')
    op.drop_column('game', 'image_banner')
    # ### end Alembic commands ###
