"""empty message

Revision ID: 533ad4e4fc3a
Revises: 303de1a7b1cd
Create Date: 2021-05-04 17:16:21.124728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '533ad4e4fc3a'
down_revision = '303de1a7b1cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('game', 'developer',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('game', 'discount',
               existing_type=sa.NUMERIC(precision=2, scale=2),
               nullable=True)
    op.alter_column('game', 'features',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('game', 'languages',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('game', 'max_graphics',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('game', 'max_memory',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('game', 'max_os',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('game', 'max_processor',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('game', 'max_storage',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('game', 'min_graphics',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('game', 'min_memory',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('game', 'min_os',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('game', 'min_processor',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('game', 'min_storage',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('game', 'other_details',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('game', 'price',
               existing_type=sa.NUMERIC(precision=2, scale=2),
               nullable=True)
    op.alter_column('game', 'publisher',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('game', 'rating',
               existing_type=sa.NUMERIC(precision=2, scale=1),
               nullable=True)
    op.alter_column('game', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('game', 'rating',
               existing_type=sa.NUMERIC(precision=2, scale=1),
               nullable=False)
    op.alter_column('game', 'publisher',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('game', 'price',
               existing_type=sa.NUMERIC(precision=2, scale=2),
               nullable=False)
    op.alter_column('game', 'other_details',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('game', 'min_storage',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('game', 'min_processor',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('game', 'min_os',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('game', 'min_memory',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('game', 'min_graphics',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('game', 'max_storage',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('game', 'max_processor',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('game', 'max_os',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('game', 'max_memory',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('game', 'max_graphics',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('game', 'languages',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('game', 'features',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('game', 'discount',
               existing_type=sa.NUMERIC(precision=2, scale=2),
               nullable=False)
    op.alter_column('game', 'developer',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('game', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
