"""empty message

Revision ID: 59202d403b5f
Revises: fef60d34b70a
Create Date: 2021-05-09 01:04:38.286499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59202d403b5f'
down_revision = 'fef60d34b70a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_name', sa.String(length=32), nullable=False),
    sa.Column('setting_value', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setting_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('website_setting')
    # ### end Alembic commands ###
