"""empty message

Revision ID: 5a5f73ffe458
Revises: 99bc9fffb346
Create Date: 2021-05-10 20:39:49.375204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a5f73ffe458'
down_revision = '99bc9fffb346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_game',
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], )
    )
    op.drop_table('review_game_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_game_user',
    sa.Column('review_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name='review_game_user_game_id_fkey'),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], name='review_game_user_review_id_fkey')
    )
    op.drop_table('review_game')
    # ### end Alembic commands ###
