"""empty message

Revision ID: 818a4e0ee415
Revises: 278efc1a7020
Create Date: 2021-05-08 22:42:24.379650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818a4e0ee415'
down_revision = '278efc1a7020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('discount_expirable', sa.Boolean(), nullable=True))
    op.add_column('game', sa.Column('discount_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'discount_expiry')
    op.drop_column('game', 'discount_expirable')
    # ### end Alembic commands ###
