"""empty message

Revision ID: 84c1b703be2a
Revises: 7e0043a47839
Create Date: 2021-05-10 23:14:15.475245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84c1b703be2a'
down_revision = '7e0043a47839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'languages',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=160),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'languages',
               existing_type=sa.String(length=160),
               type_=sa.VARCHAR(length=60),
               existing_nullable=True)
    # ### end Alembic commands ###
