"""empty message

Revision ID: 87c36a0fa500
Revises: b1e1e5875e36
Create Date: 2021-05-10 20:51:10.274167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87c36a0fa500'
down_revision = 'b1e1e5875e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_game')
    op.drop_table('review_user')
    op.alter_column('review', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('review', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('review', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('review', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('review', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('review_user',
    sa.Column('review_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], name='review_user_review_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name='review_user_user_id_fkey')
    )
    op.create_table('review_game',
    sa.Column('review_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name='review_game_game_id_fkey'),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], name='review_game_review_id_fkey')
    )
    # ### end Alembic commands ###
