"""empty message

Revision ID: b1e1e5875e36
Revises: 5a5f73ffe458
Create Date: 2021-05-10 20:43:20.916052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e1e5875e36'
down_revision = '5a5f73ffe458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review_game', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('review_game', 'review_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('review_user', 'review_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('review_user', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review_user', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('review_user', 'review_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('review_game', 'review_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('review_game', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
