"""empty message

Revision ID: d51b2822af88
Revises: d144c2b305d7
Create Date: 2021-05-05 13:42:11.107005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd51b2822af88'
down_revision = 'd144c2b305d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('platform_name_key', 'platform', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('platform_name_key', 'platform', ['name'])
    # ### end Alembic commands ###
