"""empty message

Revision ID: fcaf64a304e1
Revises: b6c7c72189bb
Create Date: 2021-04-22 19:24:17.343334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcaf64a304e1'
down_revision = 'b6c7c72189bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('discount', sa.Numeric(precision=2, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'discount')
    # ### end Alembic commands ###
