"""empty message

Revision ID: fef60d34b70a
Revises: 818a4e0ee415
Create Date: 2021-05-08 23:02:24.170312

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fef60d34b70a'
down_revision = '818a4e0ee415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('discount_end_date', sa.DateTime(), nullable=True))
    op.add_column('game', sa.Column('discount_start_date', sa.DateTime(), nullable=True))
    op.drop_column('game', 'discount_expiry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('discount_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('game', 'discount_start_date')
    op.drop_column('game', 'discount_end_date')
    # ### end Alembic commands ###
